## STAGE 1: DATA CLEANING

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("mbti_1.csv")

In [3]:
df

      type                                              posts
0     INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1     ENTP  'I'm finding the lack of me in these posts ver...
2     INTP  'Good one  _____   https://www.youtube.com/wat...
3     INTJ  'Dear INTP,   I enjoyed our conversation the o...
4     ENTJ  'You're fired.|||That's another silly misconce...
...    ...                                                ...
8670  ISFP  'https://www.youtube.com/watch?v=t8edHB_h908||...
8671  ENFP  'So...if this thread already exists someplace ...
8672  INTP  'So many questions when i do these things.  I ...
8673  INFP  'I am very conflicted right now when it comes ...
8674  INFP  'It has been too long since I have been on per...

[8675 rows x 2 columns]

In [4]:
# We will first clean the dataset by dropping any missing rows(if there arre any)
df=df.dropna(how="any")

In [5]:
# We will remove any links to make it easier for our model to input the data. 
# These links don't tell us much about the person's personality to begin with aswell
df['posts'] = df['posts'].str.replace(r'http\S+', '', regex=True)
df

      type                                              posts
0     INFJ  ' and intj moments    sportscenter not top ten...
1     ENTP  'I'm finding the lack of me in these posts ver...
2     INTP  'Good one  _____    course, to which I say I k...
3     INTJ  'Dear INTP,   I enjoyed our conversation the o...
4     ENTJ  'You're fired.|||That's another silly misconce...
...    ...                                                ...
8670  ISFP  ' just because I always think of cats as Fi do...
8671  ENFP  'So...if this thread already exists someplace ...
8672  INTP  'So many questions when i do these things.  I ...
8673  INFP  'I am very conflicted right now when it comes ...
8674  INFP  'It has been too long since I have been on per...

[8675 rows x 2 columns]

In [6]:
# We want to simplify the types. Instead of focusing on 16 different personality types, 
# we will just create a new column and generalise these 16 personality types into two types 
# Introvert (I) vs Extrovert(E))
df["personality_type"]=df["type"].str[0]
df

      type                                              posts personality_type
0     INFJ  ' and intj moments    sportscenter not top ten...                I
1     ENTP  'I'm finding the lack of me in these posts ver...                E
2     INTP  'Good one  _____    course, to which I say I k...                I
3     INTJ  'Dear INTP,   I enjoyed our conversation the o...                I
4     ENTJ  'You're fired.|||That's another silly misconce...                E
...    ...                                                ...              ...
8670  ISFP  ' just because I always think of cats as Fi do...                I
8671  ENFP  'So...if this thread already exists someplace ...                E
8672  INTP  'So many questions when i do these things.  I ...                I
8673  INFP  'I am very conflicted right now when it comes ...                I
8674  INFP  'It has been too long since I have been on per...                I

[8675 rows x 3 columns]

In [7]:
df=df[["posts","type","personality_type"]]
df

                                                  posts  type personality_type
0     ' and intj moments    sportscenter not top ten...  INFJ                I
1     'I'm finding the lack of me in these posts ver...  ENTP                E
2     'Good one  _____    course, to which I say I k...  INTP                I
3     'Dear INTP,   I enjoyed our conversation the o...  INTJ                I
4     'You're fired.|||That's another silly misconce...  ENTJ                E
...                                                 ...   ...              ...
8670  ' just because I always think of cats as Fi do...  ISFP                I
8671  'So...if this thread already exists someplace ...  ENFP                E
8672  'So many questions when i do these things.  I ...  INTP                I
8673  'I am very conflicted right now when it comes ...  INFP                I
8674  'It has been too long since I have been on per...  INFP                I

[8675 rows x 3 columns]

In [8]:
# We now need to remove a records that mention any of the 16 persoanltity types (infj, entp and etc) and other cheat words
# Sometimes people will give away their personality type when typing, this is a cheat and will reduce our models accuracy.
df=df.copy()
mbti_types=["istj", "isfj", "infj", "intj", "istp", "isfp", 
            "infp", "intp", "estp", "esfp", "enfp", "entp", "estj", 
            "esfj", "enfj", "entj",  "introvert", "extrovert", "introversion", "extroversion", "introverted", "extroverted"]

df["cleaned_posts"]=df["posts"].str.lower()


for word in mbti_types:
    df["cleaned_posts"]=df["cleaned_posts"].str.replace(word, " ")

df=df[["posts","cleaned_posts","type","personality_type"]]
df

,posts,cleaned_posts,type,personality_type
0,' and intj moments sportscenter not top ten...,' and moments sportscenter not top ten pl...,INFJ,I
1,'I'm finding the lack of me in these posts ver...,'i'm finding the lack of me in these posts ver...,ENTP,E
2,"'Good one _____ course, to which I say I k...","'good one _____ course, to which i say i k...",INTP,I
3,"'Dear INTP, I enjoyed our conversation the o...","'dear , i enjoyed our conversation the othe...",INTJ,I
4,'You're fired.|||That's another silly misconce...,'you're fired.|||that's another silly misconce...,ENTJ,E
...,...,...,...,...
8670,' just because I always think of cats as Fi do...,' just because i always think of cats as fi do...,ISFP,I
8671,'So...if this thread already exists someplace ...,'so...if this thread already exists someplace ...,ENFP,E
8672,'So many questions when i do these things. I ...,'so many questions when i do these things. i ...,INTP,I
8673,'I am very conflicted right now when it comes ...,'i am very conflicted right now when it comes ...,INFP,I
8674,'It has been too long since I have been on per...,'it has been too long since i have been on per...,INFP,I

In [9]:
# We will now remove the pipe operators(|||) that seperate the diffeerent entires someone made.
# We do this so that our ML model will be able to be more accurate and have less noise to work with

df["cleaned_posts"]= df["cleaned_posts"].str.replace("|||", " ", regex=False)
df

,posts,cleaned_posts,type,personality_type
0,' and intj moments sportscenter not top ten...,' and moments sportscenter not top ten pl...,INFJ,I
1,'I'm finding the lack of me in these posts ver...,'i'm finding the lack of me in these posts ver...,ENTP,E
2,"'Good one _____ course, to which I say I k...","'good one _____ course, to which i say i k...",INTP,I
3,"'Dear INTP, I enjoyed our conversation the o...","'dear , i enjoyed our conversation the othe...",INTJ,I
4,'You're fired.|||That's another silly misconce...,'you're fired. that's another silly misconcept...,ENTJ,E
...,...,...,...,...
8670,' just because I always think of cats as Fi do...,' just because i always think of cats as fi do...,ISFP,I
8671,'So...if this thread already exists someplace ...,'so...if this thread already exists someplace ...,ENFP,E
8672,'So many questions when i do these things. I ...,'so many questions when i do these things. i ...,INTP,I
8673,'I am very conflicted right now when it comes ...,'i am very conflicted right now when it comes ...,INFP,I
8674,'It has been too long since I have been on per...,'it has been too long since i have been on per...,INFP,I

In [10]:
# My dataset is now cleaned, I save it as a csv to to work on for the EDA?Visualisations part
df.to_csv("cleaned_data.csv", index=False)

## Phase 3: Export data to mySQL

In [ ]:
# We use the create_engine function to connect to mySQL server
import os
import urllib.parse
from sqlalchemy import create_engine
from dotenv import load_dotenv

# Load variables from .env file
load_dotenv()

# Get and encode password
raw_pass = os.getenv("DB_PASSWORD")
password = urllib.parse.quote_plus(raw_pass)

# Connect and Upload
engine = create_engine(f"mysql+pymysql://root:{password}@localhost/therapy_db")
df.to_sql("patient_records", con=engine, if_exists='replace', index=False)

## Phase 2: ML model

In [11]:
# Since my ML model can only understand numbers, we will start by converting our personality types to numbers (0 and 1)
df["encoded_type"]=df["personality_type"].replace({"I":0,"E":1})

C:\Users\Admin\AppData\Local\Temp\ipykernel_20164\4156234108.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["encoded_type"]=df["personality_type"].replace({"I":0,"E":1})

In [12]:
df

,posts,cleaned_posts,type,personality_type,encoded_type
0,' and intj moments sportscenter not top ten...,' and moments sportscenter not top ten pl...,INFJ,I,0
1,'I'm finding the lack of me in these posts ver...,'i'm finding the lack of me in these posts ver...,ENTP,E,1
2,"'Good one _____ course, to which I say I k...","'good one _____ course, to which i say i k...",INTP,I,0
3,"'Dear INTP, I enjoyed our conversation the o...","'dear , i enjoyed our conversation the othe...",INTJ,I,0
4,'You're fired.|||That's another silly misconce...,'you're fired. that's another silly misconcept...,ENTJ,E,1
...,...,...,...,...,...
8670,' just because I always think of cats as Fi do...,' just because i always think of cats as fi do...,ISFP,I,0
8671,'So...if this thread already exists someplace ...,'so...if this thread already exists someplace ...,ENFP,E,1
8672,'So many questions when i do these things. I ...,'so many questions when i do these things. i ...,INTP,I,0
8673,'I am very conflicted right now when it comes ...,'i am very conflicted right now when it comes ...,INFP,I,0
8674,'It has been too long since I have been on per...,'it has been too long since i have been on per...,INFP,I,0

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Here we transform our cleaned_posts column to a matrix of word importance scores using tf-idf vectorization
# the stop_words takes out all the common and boring English  words that people may use when typing like "the", "and", "this" and etc,
# We take out these words to reduce noise for our model
# max_features stops the model from getting distracted or misused from finding unecasary/rare words

tfidf=TfidfVectorizer(stop_words="english", max_features=5000)
X=tfidf.fit_transform(df["cleaned_posts"])
y=df["encoded_type"]

In [14]:
from sklearn.model_selection import train_test_split

#Here we are splitting our data into training and testing
# 20% of the data will be used to test while 80% of the data will be used to train
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=42, test_size=0.2)

In [15]:
from sklearn.linear_model import LogisticRegression
# Now we create our model and train it
# We set our max_iter to 1000 so that the model has 1000 chances to try predict/guess the correct personality type before it has to quit and move on to the next person.
# Made class_weight balanced so that our model places equal importance amongst introverts and extroverts(the minority in this dataset)
model = LogisticRegression(max_iter=1000, class_weight="balanced")

model.fit(X_train, y_train)

print("Model training complete!")

Model training complete!

In [16]:
from sklearn.metrics import accuracy_score, classification_report
# We now use our model to predict the our testing data
y_pred = model.predict(X_test)

# We then get the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Then we get the classification report of the model
print(classification_report(y_test, y_pred))

Model Accuracy: 74.93%
              precision    recall  f1-score   support

           0       0.88      0.79      0.83      1353
           1       0.45      0.61      0.52       382

    accuracy                           0.75      1735
   macro avg       0.66      0.70      0.67      1735
weighted avg       0.78      0.75      0.76      1735

## User response

In [ ]:
# We ask for user input (our model will then predict what personality type the user is)
user_response = input("After a long, stressful week, how do you prefer to spend your Saturday evening to feel like 'yourself' again, and why?")


tfidf_person = tfidf.transform([user_response])

# We predict the users personality type
result = model.predict(tfidf_person)

# We then work out the probability of a users irtoversion vs extroversion
probability= model.predict_proba(tfidf_person)
introvert_chance = probability[0][0]
extrovert_chance = probability[0][1]

if result[0]==1:
    print("Our model predicts that this person is an Extrovert.", "Confidence level: ", round((extrovert_chance*100),2),"%")
else:
    
    print("Our model predicts that this person is an Introvert.","Confidence level: ", round((introvert_chance*100),2),"%")

## Exporting model results and info/report

In [142]:
# Here we will create a dataframe to save the model's results for the dataset's (MBTI) tested data (that 20% test data).
y_probability=model.predict_proba(X_test)
model_results=pd.DataFrame({"Actual_type": y_test, 
                            "Predicted_type":y_pred, 
                            "Confidence_score": [max(prob) for prob in y_probability]}) 

# We then exort this as a csv
model_results.to_csv("people_results.csv", index=False)

In [143]:
# Here we will create a dataframe for the model's classification report/info
stats = classification_report(y_test, y_pred, output_dict=True)
Model_info = pd.DataFrame(stats).transpose()

# We then export this as a csv
Model_info.to_csv("model_performance_stats.csv")